# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'windows-latest'



steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.14.0'
  displayName: 'Install Node.js'

- script: |
    npm --prefix ./frontend/Cloud-Resume-UI install
    npm --prefix ./frontend/Cloud-Resume-UI run build 
  displayName: 'npm install and build'
