# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'



steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: |
    npm --prefix ./frontend/Cloud-Resume-UI install
    npm --prefix ./frontend/Cloud-Resume-UI run build 
  displayName: 'npm install and build'
  
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/build/'
    Contents: |
          $(System.DefaultWorkingDirectory)/build/**/*
    TargetFolder: '$(Build.ArtifactStagingDirectory)/output-site'
  displayName: 'Copy site files to artifact directory'

- task: ArchiveFiles@2
  displayName: "Archive Files"
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
